version: "3.9"

services:
  codegen:
    image: ballcat-codegen:latest
    container_name: ballcat-codegen
    restart: always
    ports:
      - "7777:7777"
    volumes:
      - "./logs:/workspace/logs"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - JAVA_OPTS=-Xmx256m -Xms256m -Xmn256m -Xss1m
      - DB_HOST=192.168.1.66
      - DB_PORT=3306
      - DB_NAME=ballcat_codegen
      - DB_USER=root
      - DB_PASSWORD=root
